import Head from 'next/head'

import AppHeader from '../AppHeader'
import AppFooter from '../AppFooter'

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Iris Makes Food </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <AppHeader />
        <main>{children}</main>
      </main>
      <AppFooter />
    </>
  )
}
