import Head from 'next/head'

import AppHeader from '../components/AppHeader'
import PostComponent from '../components/PostComponent'
import AppFooter from '../components/AppFooter'
import Socials from '../components/Socials'
import Copyright from '../components/Copyright'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Iris Makes Food </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <AppHeader />

      <main>
        <PostComponent />
      </main>

      <AppFooter />
      <Socials />
      <Copyright />
    </div>
  )
}
