import Head from 'next/head'
import { request } from '../lib/datocms'

import AppHeader from '../components/AppHeader'
import NewestPostsBlock from '../components/NewestPostsBlock'
import AppFooter from '../components/AppFooter'
import Socials from '../components/Socials'
import Copyright from '../components/Copyright'

const HOMEPAGE_QUERY = `query HomePage {
  test {
    test
  }
}`

export async function getStaticProps() {
  const data = await request({
    query: HOMEPAGE_QUERY,
  })
  return {
    props: { data },
  }
}

export default function Home({ data }) {
  console.log(data)
  return (
    <div>
      <Head>
        <title>Iris Makes Food </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <AppHeader />

      <main>
        <h1>hi, testing</h1>
        <NewestPostsBlock />
      </main>

      <AppFooter />
      <Socials />
      <Copyright />
    </div>
  )
}
